name    'AlexCline-dirtree'
version '0.2.1'
author 'Alex Cline <alex.cline@gmail.com>'
license 'Apache License, Version 2.0'
summary 'The dirtree function builds an array of directories from a full directory path or an array of full directory paths.  The array can then be used to ensure all the required directories in a path are managed by puppet.'
description 'The dirtree function builds an array of directories from a full directory path or an array of full directory paths.  The array can then be used to ensure all the required directories in a path are managed by puppet.'
project_page 'https://github.com/AlexCline/dirtree'
