name    'hajee-easy_type'
version '0.13.0'
source 'http:/www.github.com/hajee/easy_type'
author 'Bert Hajee'
license 'Apache License, Version 2.0'
summary 'An easy way to build a custom puppet resource'
description 'An easy way to build a complex custom puppet resource'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'

